### ISSUE TITLE
Visualization problems when used in Dashboards.

### ISSUE THREAD

**Issue by gaby** [snuids/TrafficLightVisKibana6#3]
I noticed the Visualization Legend doesn't show up, and there's no way to disable it. I only realised this after adding them to a dashboard. This makes the traffic lights panel to have a lot of empty space to the right when added to dashboards.

I also noted that when adding to dashboards and resizing the panel, all the traffic lights merge into 1. Most of the visualizations add a scroll bar when the panel is too small.

**Comment by snuids** [comment]
@ gabrielcalderon

I added a fixed size mode that should solve your display problems. I also added another display mode using simple rectangles.

Cheers,

**Comment by gaby** [comment]
Awesome! I'll give it a try this week.

**Comment by gaby** [comment]
@snuids Seems to be working fine for me now :-)
