### ISSUE TITLE
Brach for kibana 7.6

### ISSUE THREAD

**Issue by cavamagie** [snuids/TrafficLightVisKibana6#7]
thanks

**Comment by snuids** [comment]
Did you try with the 7.2 branch ?

**Comment by cavamagie** [comment]
no... but now i try

**Comment by Cruisin1966** [comment]
It does not work with Kibana 7.6  It seems there is no longer a 'ui/vis/' structure.  Looks like there's some sort of reference to a 'legacy' folder structure that doesn't set up the same way.  The documentation provided by Kibana 7.6 is not correct: https://www.elastic.co/guide/en/kibana/current/development-visualization-factory.html

Errors:
FATAL  Error: Optimizations failure.
   9262 modules
    
    ERROR in ./plugins/TrafficLightVisKibana6-7.2/public/trafficlightvis.js
    Module not found: Error: Can't resolve 'ui/registry/vis_types' in '/usr/share/kibana/plugins/TrafficLightVisKibana6-7.2/public'
    
    ERROR in ./plugins/TrafficLightVisKibana6-7.2/public/trafficlightvis.js
    Module not found: Error: Can't resolve 'ui/vis/vis_factory' in '/usr/share/kibana/plugins/TrafficLightVisKibana6-7.2/public'

**Comment by snuids** [comment]
That's a nightmare. They change things all the time. I will try to have a look when I am upgrading my Kibana to 7.6. I am currently using 7.4.

**Comment by Cruisin1966** [comment]
The only example I have found in the elastic discussions isn't clear by any means.

**Comment by Cruisin1966** [comment]
And even in 7.4, the structure in question is found in '/src/legacy/ui/public/vis/' vs. 6.8 which is 'src/ui/public/vis/'  No such structure exists in 7.6

**Comment by ch-bas** [comment]
This should be closed by [#8](https://github.com/snuids/TrafficLightVisKibana6/pull/8).

**Comment by snuids** [comment]
Thanks to ch-bas it looks like we have a working 7.6 version.
